---
- name: Setup Linux Metrics Collection on Multiple Servers
  hosts: slaves
  become: yes
  tasks:

    - name: Install Python, Pip, and Cron
      package:
        name:
          - python3
          - python3-pip
          - cronie  # 'cronie' is the cron package for Amazon Linux & RHEL-based systems
        state: present
        update_cache: yes          

    - name: Install Python dependencies
      pip:
        name:
          - psutil
          - mysql-connector-python
        state: present

    - name: Deploy Python Script for Metrics Collection
      copy:
        dest: /opt/linux_metrics.py
        mode: "0755"
        content: |
          import psutil
          import mysql.connector
          from datetime import datetime
          import socket

          # Database Configuration (Central MySQL Server)
          db_config = {
              "host": "{{ controller_ip }}",
              "user": "metrics_user",
              "password": "MySecurePassword",
              "database": "system_metrics"
          }

          def get_system_metrics():
              cpu_usage = psutil.cpu_percent(interval=1)
              memory_usage = psutil.virtual_memory().percent
              disk_usage = psutil.disk_usage('/').percent
              hostname = socket.gethostname()
              return hostname, cpu_usage, memory_usage, disk_usage

          def insert_into_db(hostname, cpu, memory, disk):
              try:
                  conn = mysql.connector.connect(**db_config)
                  cursor = conn.cursor()
                  sql = "INSERT INTO metrics (server_name, cpu_usage, memory_usage, disk_usage) VALUES (%s, %s, %s, %s)"
                  cursor.execute(sql, (hostname, cpu, memory, disk))
                  conn.commit()
                  cursor.close()
                  conn.close()
                  print(f"[{datetime.now()}] {hostname} - CPU={cpu}%, RAM={memory}%, Disk={disk}%")
              except Exception as e:
                  print("Database Error:", e)

          if __name__ == "__main__":
              hostname, cpu, memory, disk = get_system_metrics()
              insert_into_db(hostname, cpu, memory, disk)

    - name: Setup Cron Job for Data Collection
      cron:
        name: "Linux Metrics Collection"
        minute: "*/1"
        job: "/usr/bin/python3 /opt/linux_metrics.py"
        state: present
        user: ec2-user

    - name: Ensure Cron Service Is Running and Restart It
      service:
        name: crond
        state: restarted
        enabled: yes

    - name: Debug controller IP
      debug:
        msg: "Controller IP is {{ controller_ip }}"