---
- name: Install and Configure Prometheus Node Exporter on Ubuntu
  hosts: slaves
  become: yes
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name:
          - wget
          - tar
        state: present

    - name: Download Node Exporter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter.tar.gz"

    - name: Extract Node Exporter
      ansible.builtin.unarchive:
        src: "/tmp/node_exporter.tar.gz"
        dest: "/usr/local/bin/"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Create Node Exporter system user
      user:
        name: node_exporter
        system: yes
        shell: /bin/false

    - name: Set permissions for Node Exporter binary
      file:
        path: "/usr/local/bin/node_exporter"
        owner: node_exporter
        group: node_exporter
        mode: "0755"

    - name: Create systemd service file for Node Exporter
      copy:
        dest: "/etc/systemd/system/node_exporter.service"
        mode: "0644"
        content: |
          [Unit]
          Description=Prometheus Node Exporter
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=node_exporter
          Group=node_exporter
          Type=simple
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start Node Exporter service
      systemd:
        name: node_exporter
        state: started
        enabled: yes
